-- to read a blob
select UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(TEXT, 2000,1)) from RFD_SHADOW_LOG;


--interval partitions example
CREATE TABLE CHECK_PARTITIONS (
  "ID" NUMBER NOT NULL,
  "USER_SIGN" VARCHAR2(20),
  "CORR_ID" VARCHAR2(14) NOT NULL,
  "TIME_STAMP" DATE NOT NULL
)
PARTITION BY RANGE("TIME_STAMP")
    INTERVAL(NUMTODSINTERVAL(2, 'MINUTE'))
    --INTERVAL(NUMTOYMINTERVAL(2, 'MONTH'))
    (PARTITION PARTCRB_HISTORY_20160101 VALUES LESS THAN (TO_DATE('2015-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'))
);

--get CURRENT_TIMESTAMP
SELECT CURRENT_TIMESTAMP FROM DUAL

--to check partitions
SELECT table_name, partition_name, compression FROM user_tab_partitions where table_name like 'CHECK_PARTITIONS_2';

--Partitioning update
CREATE TABLE CHECK_PARTITIONS_2 (
  "ID" NUMBER NOT NULL,
  "USER_SIGN" VARCHAR2(20),
  "CORR_ID" VARCHAR2(14) NOT NULL,
  "TIME_STAMP" DATE NOT NULL
)
PARTITION BY RANGE("TIME_STAMP")(
    PARTITION t0 VALUES LESS THAN (TO_DATE('2015-12-22 14:52:00','YYYY-MM-DD HH24:MI:SS')),
    PARTITION t1 VALUES LESS THAN (TO_DATE('2015-12-22 14:54:00','YYYY-MM-DD HH24:MI:SS')),
    PARTITION t2 VALUES LESS THAN (TO_DATE('2015-12-22 14:56:00','YYYY-MM-DD HH24:MI:SS')),
   PARTITION t3 VALUES LESS THAN (TO_DATE('2015-12-22 14:58:00','YYYY-MM-DD HH24:MI:SS'))
);

ALTER TABLE CHECK_PARTITIONS_2
SET INTERVAL(NUMTODSINTERVAL(30, 'SECOND'))

--check loaded version
alter session set nls_date_format='DD/MM/YYYY HH24:MI:SS';
alter session set current_schema=DBAREFPRD ;
set pages 300 lines 300

COL RELEASE_NUMBER FORMAT A14
SELECT RELEASE_NUMBER, LAST_UPD_DATE
FROM DATABASE_RELEASE;

-- so that you can see dates in a nice way

ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH24:MI:SS';